### ISSUE TITLE
一直提示[*] waiting for crawl proxy... 是不是我的姿势哪里不对

### ISSUE THREAD

**Issue by CtrlAltDelet** [Liang2580/rotateproxy#1]
![image](https://user-images.githubusercontent.com/38282439/143045080-7ee13718-9cf6-4bfa-83ff-b315296d8e4b.png)

**Comment by CtrlAltDelet** [comment]
./rotateproxy -email xxx@qq.com -page 5 -token xxxxxxxxxxxxxxxxxxxxxxx -rule "protocol==\"socks5\" && \"Version:5 Method:No Authentication(0x00)\" && after=\"2021-08-01\" && country=\"CN\""

**Comment by CtrlAltDelet** [comment]
`./rotateproxy -email 627861816@qq.com -page 5 -token e41c59f007b68138add304142123a3a3 -rule "protocol==\"socks5\" && \"Version:5 Method:No Authentication(0x00)\" && after=\"2021-08-01\" && country=\"CN\""`

**Comment by Liang2580** [comment]
你先删除那个db 文件。
使用2.0 的编译一下 
代码如下：https://github.com/Liang2580/rotateproxy/tree/2.0

**Comment by Liang2580** [comment]
rm -rf db.db  
然后编译一下。或者使用我上传的2.0 的那个文件也行。

**Comment by CtrlAltDelet** [comment]
下载了 还是一样的问题 先谢啦
